[2025-03-21T19:43:11.924+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T19:43:11.929+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_dag.train_model manual__2025-03-21T14:43:09.565548+00:00 [queued]>
[2025-03-21T19:43:11.932+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_dag.train_model manual__2025-03-21T14:43:09.565548+00:00 [queued]>
[2025-03-21T19:43:11.932+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T19:43:11.943+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): train_model> on 2025-03-21 14:43:09.565548+00:00
[2025-03-21T19:43:11.945+0500] {standard_task_runner.py:72} INFO - Started process 158852 to run task
[2025-03-21T19:43:11.947+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'train_dag', 'train_model', 'manual__2025-03-21T14:43:09.565548+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmps06iyk7x']
[2025-03-21T19:43:11.947+0500] {standard_task_runner.py:105} INFO - Job 2: Subtask train_model
[2025-03-21T19:43:11.970+0500] {task_command.py:467} INFO - Running <TaskInstance: train_dag.train_model manual__2025-03-21T14:43:09.565548+00:00 [running]> on host DESKTOP-LSRPTF5.
[2025-03-21T19:43:12.007+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='train_dag' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T14:43:09.565548+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T14:43:09.565548+00:00'
[2025-03-21T19:43:12.008+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T19:43:12.008+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T19:43:12.008+0500] {logging_mixin.py:190} INFO - Current task name:train_model state:running start_date:2025-03-21 14:43:11.930087+00:00
[2025-03-21T19:43:12.008+0500] {logging_mixin.py:190} INFO - Dag name:train_dag and current dag run status:running
[2025-03-21T19:43:12.008+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T19:43:12.009+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/metro/airflow/dags/main.py", line 12, in train_model
    con = sqlite3.connect('data/db.db')
sqlite3.OperationalError: unable to open database file
[2025-03-21T19:43:12.012+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T19:43:12.012+0500] {logging_mixin.py:190} INFO - Task start:2025-03-21 14:43:11.930087+00:00 end:2025-03-21 14:43:12.012353+00:00 duration:0.082266
[2025-03-21T19:43:12.012+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): train_model> dag:<DAG: train_dag> dagrun:<DagRun train_dag @ 2025-03-21 14:43:09.565548+00:00: manual__2025-03-21T14:43:09.565548+00:00, state:running, queued_at: 2025-03-21 14:43:09.581751+00:00. externally triggered: True>
[2025-03-21T19:43:12.013+0500] {logging_mixin.py:190} INFO - Failure caused by unable to open database file
[2025-03-21T19:43:12.013+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=train_dag, task_id=train_model, run_id=manual__2025-03-21T14:43:09.565548+00:00, execution_date=20250321T144309, start_date=20250321T144311, end_date=20250321T144312
[2025-03-21T19:43:12.028+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T19:43:12.029+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task train_model (unable to open database file; 158852)
Traceback (most recent call last):
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/ruslan/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/ruslan/metro/airflow/dags/main.py", line 12, in train_model
    con = sqlite3.connect('data/db.db')
sqlite3.OperationalError: unable to open database file
[2025-03-21T19:43:12.040+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T19:43:12.046+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T19:43:12.046+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
